services:
  django_db:
    container_name: roomsforyou
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 30s
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrations:
    build: .
    env_file: .env
    command: python manage.py migrate
    volumes:
      - .:/code
    depends_on:
      django_db:
        condition: service_healthy

  web:
    build: .
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    stdin_open: true
    tty: true
    ports:
      - 8000:8000

    depends_on:
      django_db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
volumes:
  pgdata:
